package com.luxsoft.nace.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.Objects;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "nace")
@JsonIgnoreProperties
public class NaceEntity {

    @ApiModelProperty(notes = "Technical Field",name="Id", required=true, value="autogenerated")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "seqGen")
    @SequenceGenerator(name = "seqGen", sequenceName = "seq", initialValue = 1)
    private Long id;

    @ApiModelProperty(notes = "Order id",name="Order",required=true,value="1")
    @Column(name = "orderid")
    private String order;
    private String level;
    private String code;
    private String description;
    private String reference;

    public NaceEntity() {}

    public NaceEntity(String order, String level, String code, String description, String reference) {
        this.order = order;
        this.level = level;
        this.code = code;
        this.description = description;
        this.reference = reference;
    }


    public String getOrder() {
        return order;
    }

    public void setOrder(String order) {
        this.order = order;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NaceEntity that = (NaceEntity) o;
        return order.equals(that.order) &&
                Objects.equals(level, that.level) &&
                Objects.equals(code, that.code) &&
                Objects.equals(description, that.description) &&
                Objects.equals(reference, that.reference);
    }

    @Override
    public int hashCode() {
        return Objects.hash(order, level, code, description, reference);
    }
}
